django_tutorial/first_project/api_server/urls.py
from django.conf.urls import url
from api_server import views

app_name = 'api_server'
urlpatterns = [
    url(r'^v1/regions$', views.regions, name='regions'),
    url(r'^v1/businesses$', views.businesses, name='businesses')
]

django_tutorial/first_project/first_project/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include('api_server.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('web_app.urls')),
]

django_tutorial/first_project/web_app/urls.py
from django.conf.urls import url
from web_app import views

app_name = 'web_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

django_tutorial/first_project/web_app/models.py
from django.db import models

# Create your models here.

django_tutorial/first_project/web_app/views.py
from django.shortcuts import render
from django.views.decorators.http import require_GET

@require_GET
def index(request):
    """base page for the front end app -- just static HTML, rest is rendered by JS"""
    return render(request, 'web_app/index.html')

django_tutorial/first_project/web_app/templates/web_app/index.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <title>SBA Region Analysis</title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static "web_app/css/style.css" %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
    </head>
    <body>
        <div id="root">
        </div>
        <script>
                // TODO: don't use global vars like this
                var regionsUrl = "{% url 'api_server:regions' %}"
                var businessesUrl = "{% url 'api_server:businesses' %}"
                var topoUrl = "{% static "web_app/tempdata/ca_zips_geo.json" %}"
        </script>
        <script src="{% static "web_app/js/index.bundle.js" %}"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCMkwqz_xwd2fA2nAKy5s5ruzdAIy6T354&callback=init">
        </script>
    </body>
</html>